### PR TITLE
issue#38 Added README file to run locally

### PR DESCRIPTION
**Pull request by Ankit8848**
## Checklist
Please review and check the following before submitting your pull request:

- [x] I have followed the project's coding conventions and guidelines
- [x] I have tested my changes thoroughly
- [x] I have added/updated relevant documentation
- [x] My code follows best practices and is easy to understand
- [x] I have added necessary test cases (if applicable)
- [x] All existing tests are passing
- [x] My changes do not introduce any new warnings or errors

### CODE REVIEW

**Comment by neokd** [comment]
@Ankit8848 This issue is the add the readme for Website to run it locally and not for Scripts folder. A issue is already created with the same and @js-kalsi is working on it

**Comment by Ankit8848** [comment]
@neokd what should I do, shall I close the pr?

**Comment by neokd** [comment]
Yes close the PR and create a new one for Website

**Comment by Ankit8848** [comment]
@neokd can you help me out? in my local system, I am unable to run , what steps to take to run?

**Pull request closed without merging**
