### PR TITLE
Fork count in navbar: new feature

### PR DESCRIPTION
**Pull request by rtiop**
## Description

The changes made in this pull request hopefully permit the website to dynamically display the number of forks the DataStorehouse has. **Caution**: I have not been able to test the code. It is possible that it doesn't work and shouldn't be merged.  

## Related Issues

#35 Fork Count in Navbar[Website]  This addresses that.

## Changes Made

Changed the Navbar.jsx component to call the fork counting function and display it and added a new script in the script folder (fork_count.js) to actually count the forks.

## Screenshots (if applicable)

Untested. Test before merging.

## Checklist
Please review and check the following before submitting your pull request:

- [x] I have followed the project's coding conventions and guidelines
- [ ] I have tested my changes thoroughly
- [x] I have added/updated relevant documentation
- [x] My code follows best practices and is easy to understand
- [ ] I have added necessary test cases (if applicable)
- [ ] All existing tests are passing
- [ ] My changes do not introduce any new warnings or errors

## Additional Notes

Only 60 requests can be made by hour from one unauthenticated user ([documentation here](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28)) to the Github REST API. So at some point, the function should return "Unknown".

To solve this, someone should create a key and set up the code to use it, at which point, we'll be able to do 5000 request per hour. Contributions are welcome, because ... I don't have the know-how to do it.

**The code is untested, I don't know how to preview the React web application.**
Thank you for your understanding.

### CODE REVIEW

**Comment by neokd** [comment]
@rtiop you create a function either directly in the Navbar.jsx file or have a look on Octokit.js

**Comment by neokd** [comment]
Have u tested it?

**Comment by rtiop** [comment]
No, I don't know how to preview a React web app. I opened the pull request to see if someone else could test it. I mentioned it in the description of the request.

**Comment by Priyamakeshwari** [comment]
@rtiop This is not working so I am not merging your pull request

**Pull request closed without merging**
