### PR TITLE
Created the folder and the files and added content to the files. (#32)

### PR DESCRIPTION
**Pull request by anubhav1206**

### CODE REVIEW

**Comment by neokd** [comment]
@anubhav1206 can u send screen shots so i can verify and merge the coee.

**Comment by anubhav1206** [comment]
> @anubhav1206 can u send screen shots so i can verify and merge the coee.

Sure
image

**Comment by neokd** [comment]
Thanks for your contribution @anubhav1206. Make sure you 🌟 the repo and follow us on [Linkedin](https://www.linkedin.com/in/data-storehouse-3a8326281/)

**Comment by anubhav1206** [comment]
Thank you!

**Pull request merged**
