### PR TITLE
Add requirements.txt files to ensure everyone is using the same Python env for the development

### PR DESCRIPTION
**Pull request by js-kalsi**
## Description

- Added 2 requirements.txt files:
   - For the Validation directory
   - For the script directory
- Added instructions on how to set up an environment for running Python modules

## Related Issues

Issue: #57 

## Checklist
Please review and check the following before submitting your pull request:

- [x] I have followed the project's coding conventions and guidelines
- [x] I have tested my changes thoroughly
- [x] I have added/updated relevant documentation
- [x] My code follows best practices and is easy to understand
- [ ] I have added necessary test cases (if applicable)
- [ ] All existing tests are passing
- [x] My changes do not introduce any new warnings or errors

### CODE REVIEW

**Comment by neokd** [comment]
You can put a separate README.md inside the scripts folder

**Comment by js-kalsi** [comment]
> You can put a separate README.md inside the scripts folder

Done!

**Comment by js-kalsi** [comment]
@neokd I made the changes, kindly review it, thanks

**Comment by neokd** [comment]
Thanks for your contribution

**Pull request merged**
